CREATE TABLE COURSES(
COURSE_NUMBER VARCHAR(16) NOT NULL,
TITLE VARCHAR(128) NOT NULL,
SECTION_ID INTEGER NOT NULL,
TERM VARCHAR(32) NOT NULL,
CREDIT DOUBLE NOT NULL,
DESCRIPTION VARCHAR(256) ,
INSTRUCTOR VARCHAR(64) ,
BUILDING VARCHAR(32) ,
ROOM VARCHAR(8) ,
PREREQUISITES VARCHAR(256) ,
DAYS VARCHAR(5)NOT NULL,
START_TIME TIME NOT NULL,
END_TIME TIME NOT NULL,
EXAM TIMESTAMP NOT NULL,
PRIMARY KEY (COURSE_NUMBER,SECTION_ID));

