Create table STUDENT_INFO (STUDENT_ID VARCHAR(9) not null,
STREET_ADDRESS VARCHAR(100) not null,CITY VARCHAR(50) not null,PROVINCE_STATE VARCHAR(50) not null,POSTAL_CODE VARCHAR(50) not null,COUNTRY VARCHAR(50) not null,PHONE_NUMBER VARCHAR(50) not null,EMAIL VARCHAR(50) not null);
              